name: Process Dataset

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC every day
  workflow_dispatch:
  push:
    paths:
      - 'dataset.txt'  # Trigger the workflow when dataset.txt is updated

jobs:
  update-dataset:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        echo 'No dependencies to install'

    - name: Process dataset
      run: python process_dataset.py

    - name: Commit changes
      run: |
        git config --global user.name 'Fabrizio Salmi'
        git config --global user.email 'fabrizio.salmi@gmail.com'
        git add dataset.txt boundaries.log
        git commit -m "Update dataset and boundaries"
        git push
